# Generated by Django 4.1.5 on 2023-01-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(db_index=True, default=18, verbose_name='Возраст')),
                ('job', models.CharField(choices=[(1, 'Оператор'), (3, 'Начальник'), (4, 'Уборщик'), (5, 'Учитель'), (6, 'Охранник'), (7, 'Бухгалтер'), (8, 'Администартор')], default=5, max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
