# Generated by Django 4.1.5 on 2023-01-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('Оператор', 'Оператор'), ('Начальник', 'Начальник'), ('Уборщик', 'Уборщик'), ('Учитель', 'Учитель'), ('Охранник', 'Охранник'), ('Бухгалтер', 'Бухгалтер'), ('Администартор', 'Администартор')], default=5, max_length=100, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Логин работника')),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_control.employee')),
            ],
        ),
    ]
